### ISSUE TITLE
Using precompiled binaries 

### ISSUE THREAD

**Issue by ptagl** [NordicSemiconductor/pc-ble-driver#106]
Hi,

I would like to use the PC BLE Driver in order to use a NRF51 Dongle from a C#\C++ application.
I recently downloaded the provided binaries (pc-ble-driver v2.3.0 release) for Windows64 and found several static and dynamic libraries.

I guess I could use either the DLL or the LIB version, but currently I'm facing problems with them both:

1. The DLL contains some functions that take as parameters STRUCTs that I should copy from the driver source to my C#\C++ (I think this is not ideal).

2. The LIB would fix the first problem, but I don't understand why the release binaries are missing an INCLUDE folder with the header files I need to include in my application in order to use the library.

About the point 2, I tried to copy the headers from the last commit of the source, something was missing though (for example the header "ble.h") that I found in the softdevice, but anyway I was not able to link my application because of some "unreferenced symbols" (probably the header files and the LIB are slightly different).

Could you please tell me how I should get the driver working in my application?

Thanks a lot!

**Comment by CoqRogue** [comment]
First a little bit about the background for this project: This project is intended as a thin layer providing the transport for nRF5x BLE SoftDevice connectivity, mirroring the SoftDevice interface as closely as possible. Because of this, it includes structs and other artifacts that may be hard to translate to other languages. We mostly use our bindings for JavaScript (NordicSemiconductor/pc-ble-driver-js).

As it is mostly intended as a stepping stone for our higher level bindings, we have not focused to much on making it easy to use. I do agree that we should provide the headerfiles in an include folder, and that is added to our internal issue tracker for a future release.

With regards to helping you use the drivers in you application, I would point you to our examples in the source code. For technical questions, I would recommend you checking out [Devzone](https://devzone.nordicsemi.com/) and asking questions.
